### ISSUE TITLE
Feed Bag only works in Hotbar (1.16.4)

### ISSUE THREAD

**Issue by ghost** [capnkirok/Inventory-Pets#441]
It's just that after updating the mod on our current world after a while we noticed that the feed bag wasn't working. 1.16.4 Forge server after the update

(first time posting a bug report on Github please don't hit me for being bad at describing things)

**Comment by capnkirok** [comment]
Ha! No hitting here :)

~So,I just tested and didn't see any issues. A few questions:
- Which pet is it not working for?
- Did you make sure to update both the client and server mod?
- Can you share a screenshot of the open Feed Bag?~

Thx

**Comment by capnkirok** [comment]
Actually! It looks like there is an issue with the House Pet eating from the Feed Bag. There may be a few other pets with this problem, but I know most pets should work. I will work on a fix.

This also answers your other question on why you heard the noise!

**Comment by capnkirok** [comment]
Good lord. It looks like I missed several pets. Of course the ones I tested work fine (e.g., the Chicken Pet). Will put out an update asap. 1.16 version only.

**Comment by capnkirok** [comment]
Ok, this is fixed and I've already posted to CurseForge. Look for the update and let me know!

**Comment by ghost** [comment]
> Ok, this is fixed and I've already posted to CurseForge. Look for the update and let me know!

Thank you alot! I am going to check on that

**Comment by ghost** [comment]
Also if you want you can contact me by Discord if i find another bug since me and my friend play a lot and we use the pets a lot too!
GreenMelon#5543

**Comment by ghost** [comment]
I am talking after updating to the latest version server-side and client-side
I think it is not solved entirely i have tried to use the feed bag and here is what happens:

- If the feed bag is in the inventory with food the nether portal pet does not eat

- If the feed bag is in the hotbar the pet won't eat either but it will if the bag is opened in the hotbar

- Same issues with multiple pets like the sponge pet

It also seems like it works on certain pets, the house pet works fine

**Comment by capnkirok** [comment]
Ugh. I'll have to spend more time on this and verify pet by pet. Thank you for the original post and the testing! Will let you know about next update.

**Comment by D6R** [comment]
For me, the nether pet and purpilicious pet will not eat from the bag unless the bag is in the hotbar. If it is not, the pet will not know what to eat from and won't eat until opening the bag. Same issue with the chicken pet, blaze pet, and cloud pet. As long as its in the hotbar its fine. This is only from what I've noticed. I haven't done any sort of extensive testing.

**Comment by capnkirok** [comment]
@D6R Thank you! Yes, I know exactly what's going on. Fixed one bug, created another.

**Comment by capnkirok** [comment]
Just a quick update. It's not what I thought it was, so not an easy fix. Basically, the way the current code works, the 'inventory' doesn't exist until you manually open the bag (which can only occur in the hotbar of course). Still working on it.

**Comment by capnkirok** [comment]
Ok, I figured it out. Look for the update next weekend (2.0.14).

**Comment by ghost** [comment]
> Ok, I figured it out. Look for the update next weekend (2.0.14).

Yay!
